apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-video-streaming
  labels:
    app: nginx-video-streaming
spec:
  replicas: 10  # Specify the number of replicas you want
  selector:
    matchLabels:
      app: nginx-video-streaming
  template:
    metadata:
      labels:
        app: nginx-video-streaming
    spec:
      containers:
      - name: nginx
        imagePullPolicy: IfNotPresent 
        image: nginx-video-streaming  # Docker image name
        ports:
        - containerPort: 80
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:latest
        args:
        - -nginx.scrape-uri=http://localhost:80/stub_status
        ports:
        - containerPort: 9113
