apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stream
  labels:
    app: nginx-stream
spec:
  replicas: 3  # Specify the number of replicas you want
  selector:
    matchLabels:
      app: nginx-stream
  template:
    metadata:
      labels:
        app: nginx-stream
    spec:
      containers:
      - name: nginx
        imagePullPolicy: IfNotPresent 
        image: nginx-stream  # Docker image name
        ports:
        - containerPort: 80
