apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-video-streaming
spec:
  replicas: 3  # Specify the number of replicas you want
  selector:
    matchLabels:
      app: nginx-video-streaming
  template:
    metadata:
      labels:
        app: nginx-video-streaming
    spec:
      containers:
      - name: nginx
        image: nginx-video-streaming  # Docker image name
        ports:
        - containerPort: 80
