apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  labels:
    app: mira
spec:
  endpoints:
    - interval: 15s
      port: metrics
      path: "/metrics"
  selector:
    matchLabels:
      app: mira-nginx