apiVersion: v1
kind: Service
metadata:
  name: nginx-video-streaming
spec:
  selector:
    app: nginx-video-streaming
  ports:
  - name: web
    port: 80
    targetPort: 80
    protocol: TCP
  - name: metrics
    port: 9113
    targetPort: 9113
    protocol: TCP
  type: LoadBalancer
