global:
  scrape_interval: 15s  # Default scrape interval, overridden by specific job settings

scrape_configs:
  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
      - targets: [nginx:9113]